# Generated by Django 4.2 on 2023-06-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produkitem',
            name='katalog',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='toko.sortcategory'),
        ),
    ]
