# Generated by Django 4.2 on 2023-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_sortcategory_produkitem_katalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('LE', 'Low-End'), ('MR', 'Mid-Range'), ('FS', 'Flagship')], max_length=2),
        ),
    ]
